name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: ${{ steps.doppler.outputs.DOCKER_HUB_USERNAME }}
  DOCKER_HUB_PASSWORD: ${{ steps.doppler.outputs.DOCKER_HUB_PASSWORD }}
  IMAGE_NAME: messenger-chatbot
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch Doppler Secrets
        uses: DopplerHQ/secrets-fetch-action@v1.1.0
        with:
          doppler-token: ${{ secrets.DOPPLER_SRV_DEV_TOKEN}}
      
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ env.DOCKER_HUB_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}-prod
